Enhancement #790: Expand Image
BabylonJS/Documentation pull request #1020
Opened 2023-11-27 00:23 UTC by impurity-dev

## Issue
#790 

## Description
Added a hover effect to images in the doc that allows you to expand an image in a model. I'm sure the design could be refined at some point, but it gets the job done. It is enabled by default but if in the URL your used the queryparam `expandable=false` it will disable this feature.

### Disabled
![image](https://github.com/BabylonJS/Documentation/assets/14898141/1c955241-1d21-46fc-9cfe-6d689d560348)

### Hoverable
![image](https://github.com/BabylonJS/Documentation/assets/14898141/3d0226dc-f06a-4855-87ee-8143dd9dacba)

### Hovering
![image](https://github.com/BabylonJS/Documentation/assets/14898141/a03dc83f-1224-45a1-92ad-89cbce2dedf1)

### Expanded
![image](https://github.com/BabylonJS/Documentation/assets/14898141/925654c0-d5e7-4658-9750-7fc80340fc64)

2023-11-27 16:09 UTC, RaananW requested changes
Huzzah! thanks a lot :-)

The only change I ask for is to add a close button, because on very low resolutions there is no way to close the modal if the image is expanded. 
Also, it would probably be better to have a full-screen modal on mobiles to get the image as big as possible.

2023-11-27 19:36 UTC, impurity-dev commented
> Huzzah! thanks a lot :-)
> 
> The only change I ask for is to add a close button, because on very low resolutions there is no way to close the modal if the image is expanded. Also, it would probably be better to have a full-screen modal on mobiles to get the image as big as possible.

Thanks for the feedback! On it 👍🏼

2023-11-27 20:23 UTC, RaananW commented
> > Huzzah! thanks a lot :-)
> > The only change I ask for is to add a close button, because on very low resolutions there is no way to close the modal if the image is expanded. Also, it would probably be better to have a full-screen modal on mobiles to get the image as big as possible.
> 
> Thanks for the feedback! On it 👍🏼

Amazing work, as always!

2023-11-28 11:30 UTC, RaananW approved these changes

2023-11-28 11:31 UTC, merged