Add Fog of War example in Material Plugin docs
BabylonJS/Documentation pull request #704
Opened 2022-11-09 12:06 UTC by carolhmj

2022-11-09 14:54 UTC, Popov72 requested changes

2022-11-09 14:54 UTC, Popov72 commented on content/features/featuresDeepDive/materials/using/materialPlugins.md
> +<Playground id="#8WJTJG#10" title="Simple Fog of War effect"/>
The `#ifdef COLORIFY` need to be fixed.

2022-12-01 11:24 UTC, carolhmj commented on content/features/featuresDeepDive/materials/using/materialPlugins.md
> +<Playground id="#8WJTJG#10" title="Simple Fog of War effect"/>
Fixed it, thanks for pointing it out!

2022-12-01 11:26 UTC, Popov72 approved these changes

2022-12-01 13:02 UTC, merged