Added a very simple PG in Physics Forces
BabylonJS/Documentation pull request #949
Opened 2023-08-17 06:32 UTC by flushpot1125

Hi core great contributors!
I learned Havok plugin and found no simple examples in "Forces" section.

My idea is that showing simple PGs helps for BJS beginners.

I'm very glad if you review my added PGs and any feedback would welcome. Thanks for taking your time.

2023-08-18 21:40 UTC, sebavan commented
thanks, just waiting for some of our physics ppl to review before merging :-)

2023-08-28 10:03 UTC, RaananW requested changes
Just a few working suggestions and a small request to remove the isMain

2023-08-28 10:03 UTC, RaananW commented on content/features/featuresDeepDive/physics/v2/forces.md
> +<Playground id="#Z8HTUN#671" title="applyImpulse" description="Show how to use applyImpulse in a very simple example" isMain={true} category="Physics"/>
isMain={true} is a flag we are adding to specific playgrounds and not all. Would be great if you could remove it :-)

```suggestion
<Playground id="#R66K4K" title="applyForce" description="An example of using applyForce" category="Physics"/>

<Playground id="#Z8HTUN#671" title="applyImpulse" description="An example of using applyImpule" category="Physics"/>
```

2023-08-28 10:03 UTC, RaananW commented on content/features/featuresDeepDive/physics/v2/forces.md
> +In summary, a force is a *continuous* effect over time, while an impulse is a sudden, *instantaneous* effect that changes the velocity of an object.
```suggestion
In summary, a force is a *continuous* effect over time, while an impulse is a sudden, *instantaneous* effect that changes the velocity of an object. Click on the sphere in the following examples to experiment with forces and impulses
```

2023-08-29 10:32 UTC, carolhmj requested changes
Thanks for the contribution! Just some suggestions relative to the PGs:
- I switched the force PG to apply the force in the Y-axis, so it's consistent with the impulse PG
- When applying forces/impulses, it's safer to use `absolutePosition` instead of `position`, because the body can be parented. It doesn't make a difference in this case, but it's nice to show the safer way :smile:

2023-08-29 10:32 UTC, carolhmj commented on content/features/featuresDeepDive/physics/v2/forces.md
> +<Playground id="#R66K4K" title="applyForce" description="An example of using applyForce" category="Physics"/>
```suggestion
<Playground id="#R66K4K#1" title="applyForce" description="An example of using applyForce" category="Physics"/>
```

2023-08-29 10:32 UTC, carolhmj commented on content/features/featuresDeepDive/physics/v2/forces.md
> +<Playground id="#Z8HTUN#671" title="applyImpulse" description="An example of using applyImpule" category="Physics"/>
```suggestion
<Playground id="#Z8HTUN#677" title="applyImpulse" description="An example of using applyImpule" category="Physics"/>
```

2023-08-30 11:21 UTC, RaananW commented on public/img/playgroundsAndNMEs/pg-R66K4K.png
if the playgrounds were changed, those two images are not needed (and will be generated in the next build process). They can also be renamed (add `-1` for this filename, and change `671` to `672` in the other

2023-08-30 11:22 UTC, RaananW approved these changes
my changes were merged, resetting mine.
In general - LGTM, just a small comment regarding the new playgrounds

2023-08-30 19:57 UTC, carolhmj commented
Added my changes and removed the images @RaananW it's ready to merge

2023-08-30 19:57 UTC, carolhmj approved these changes

2023-08-30 20:07 UTC, sebavan approved these changes

2023-08-30 20:07 UTC, merged

2023-08-31 14:35 UTC, flushpot1125 commented
Thanks for a lot of supporting!!!